language: java
jdk:
  - openjdk8
  - openjdk11

before_install:
  - git submodule update --init --recursive
  - sudo apt-get -qq update
  - sudo apt-get install -y ant-optional

script: 
  - "./test.sh"
  - "ant test"
  - "ant jar"

